import {
  ArrowCounterClockwise,
  ArrowsClockwise,
  BellRinging,
  BellSlash,
  CaretDown,
  CaretLeft,
  CaretRight,
  CaretUp,
  CheckCircle,
  CheckFat,
  Copy,
  DotsThreeOutlineVertical,
  Eye,
  EyeSlash,
  FloppyDisk,
  Gear,
  Image,
  Info,
  Leaf,
  Pause,
  Pencil,
  Play,
  PlusCircle,
  ShieldWarning,
  Spinner,
  Trash,
  Warning,
  WarningOctagon,
  XCircle,
  type Icon,
  type IconProps,
} from '@phosphor-icons/react'

/**
 * Every icon in the app, filled.
 *
 * The whole set is imported through this file rather than from the icon package
 * directly, for two reasons.
 *
 * **Filled is set here, once.** Phosphor draws in six weights and defaults to
 * `regular` — an outline. Passing `weight="fill"` at every call site would mean the
 * one place that forgets is the one place that looks wrong, and a global
 * `IconContext` in `main.tsx` would leave anything rendered outside that provider
 * silently back on outlines. Baking the weight into the export makes the style a
 * property of the icon, not of where it happens to be used. `weight` can still be
 * overridden per call, since props are spread after it.
 *
 * **The names are the app's, not the package's.** Call sites say `TrashIcon` and
 * `SpinnerIcon`; the mapping to Phosphor's own names lives below. That is what let
 * the whole set be swapped out from under 15 files without touching one of them —
 * they only changed which module they import from.
 *
 * `src/components/ui/**` is generated by the shadcn CLI, which writes icon imports
 * of its own — `components.json` now asks it for Phosphor rather than lucide, but it
 * still imports the package directly, and a direct import means `regular` weight.
 * After a `shadcn add`, repoint whatever it wrote at this module.
 */
function filled(Glyph: Icon) {
  return function FilledIcon(props: IconProps) {
    return <Glyph weight="fill" {...props} />
  }
}

/*
 * Four of these are not the obvious glyph, and the obvious one is wrong.
 *
 * A tick, a cross, a plus and three dots have no interior to fill, so Phosphor's
 * `fill` weight gives them a container instead and knocks the mark out of it:
 * `Check`, `X` and `Plus` come out as solid squares, `DotsThreeVertical` as a solid
 * pill. On a light primary button that is a black block with a hole in it. The
 * glyphs below are the ones that actually draw solid at this weight — check them in
 * a browser before swapping any of them back for the name you expected.
 */
export const BellOffIcon = filled(BellSlash)
export const BellRingIcon = filled(BellRinging)
export const CheckCircleIcon = filled(CheckCircle)
/** `CheckFat`, not `Check`: a solid tick rather than a solid box around one. */
export const CheckIcon = filled(CheckFat)
export const ChevronDownIcon = filled(CaretDown)
export const ChevronLeftIcon = filled(CaretLeft)
export const ChevronRightIcon = filled(CaretRight)
export const ChevronUpIcon = filled(CaretUp)
export const CopyIcon = filled(Copy)
export const EyeIcon = filled(Eye)
export const EyeOffIcon = filled(EyeSlash)
export const ImageIcon = filled(Image)
export const InfoIcon = filled(Info)
export const LeafIcon = filled(Leaf)
/** `DotsThreeOutlineVertical`, not `DotsThreeVertical`: three dots, no pill. */
export const MoreVerticalIcon = filled(DotsThreeOutlineVertical)
export const PauseIcon = filled(Pause)
export const PencilIcon = filled(Pencil)
export const PlayIcon = filled(Play)
/** A disc is the only solid plus on offer, and it reads as "add" anyway. */
export const PlusIcon = filled(PlusCircle)
export const ResetIcon = filled(ArrowCounterClockwise)
export const SaveIcon = filled(FloppyDisk)
export const SettingsIcon = filled(Gear)
export const ShieldAlertIcon = filled(ShieldWarning)
export const SpinnerIcon = filled(Spinner)
export const SyncIcon = filled(ArrowsClockwise)
export const TrashIcon = filled(Trash)
export const WarningIcon = filled(Warning)
export const WarningOctagonIcon = filled(WarningOctagon)
export const XCircleIcon = filled(XCircle)
/**
 * The same glyph as `XCircleIcon`, deliberately kept under both names: there is no
 * `XFat` to pair with `CheckFat`, so a close button and a failed-check status line
 * end up drawing the same circle. The names stay separate because they read
 * differently where they are used — `CheckCircleIcon` / `XCircleIcon` are a status
 * pair, `XIcon` is what closes a dialog.
 */
export const XIcon = filled(XCircle)
