// Generated by shadcn, with two edits: the stock component imports `useTheme`
// from next-themes, which is a Next.js dependency we don't have — it reads from
// @/state/useTheme instead. And the icons come from @/lib/icons (filled), not
// from lucide-react.
import { Toaster as Sonner, type ToasterProps } from "sonner"
import {
  CheckCircleIcon,
  InfoIcon,
  SpinnerIcon,
  WarningIcon,
  WarningOctagonIcon,
} from "@/lib/icons"

import { useTheme } from "@/state/useTheme"

const Toaster = ({ ...props }: ToasterProps) => {
  const { pref } = useTheme()

  return (
    <Sonner
      theme={pref}
      className="toaster group"
      icons={{
        success: (
          <CheckCircleIcon className="size-4" />
        ),
        info: (
          <InfoIcon className="size-4" />
        ),
        warning: (
          <WarningIcon className="size-4" />
        ),
        error: (
          <WarningOctagonIcon className="size-4" />
        ),
        loading: (
          <SpinnerIcon className="size-4 animate-spin" />
        ),
      }}
      style={
        {
          "--normal-bg": "var(--popover)",
          "--normal-text": "var(--popover-foreground)",
          "--normal-border": "var(--border)",
          "--border-radius": "var(--radius)",
        } as React.CSSProperties
      }
      toastOptions={{
        classNames: {
          toast: "cn-toast",
        },
      }}
      {...props}
    />
  )
}

export { Toaster }
